@echo off
rem Clean up variables for this session
set GOLEM_RECIPES_REPOSITORIES=
set GOLEM_ADDITIONAL_CACHE_DIRECTORIES=
set GOLEM_ADDITIONAL_READ_ONLY_CACHE_DIRECTORIES=
set GOLEM_OVERRIDES_REPOSITORY=