@echo off
rem Clean up variables for this session
set GOLEM_CACHE_DIRECTORY=
set GOLEM_ADDITIONAL_CACHE_DIRECTORIES=
set GOLEM_ADDITIONAL_READ_ONLY_CACHE_DIRECTORIES=
set GOLEM_CACHE_RESOLUTION_POLICY=
set GOLEM_CACHE_MINIMIZATION_ENABLED=
set GOLEM_CACHE_MINIMIZATION_LENGTH=
set GOLEM_GIT_FETCH_MODE=
set GOLEM_GIT_JOBS=
set GOLEM_GIT_PROMPT_ENABLED=
set GOLEM_COOKBOOKS_LOCATIONS=
set GOLEM_OVERRIDES_CONFIGURATION=
set GOLEM_OVERLAYS_LOCATIONS=
