def handle_help_command() -> None:
    print('Run `golem <command>` from your project root.')
    print('Building:')
    print('  init          Create a documented starter golemfile.py')
    print('  configure     Configure the project with all the needed options')
    print('  resolve       Retrieve and configure dependencies (if dependencies are defined)')
    print('  dependencies  Build dependencies after resolve (if dependencies are defined)')
    print('  build         Build the project')
    print('  package       Generate a package from a successful build')
    print('  clean         Remove built object files')
    print('  distclean     Delete the build directory')
    print('Managing:')
    print('  config        Get and set global or project-local settings')
    print('  tools         Manage installable tools stored in the cache')
    print('Documentation: https://golemcpp.org/docs/guides/getting-started/')
